[package]
name = "gors"
version = "0.1.0"
edition = "2021"

[lib]
name = "gors"
path = "lib.rs"

[dependencies]
log = { version = "0.4", features = ["release_max_level_warn"] }
phf = { version = "0.10", features = ["macros"] }
proc-macro2 = "1.0.33"
quote = "1.0.10"
serde = "1.0.130"
serde_json = "1.0.68"
syn = { version = "1.0.82", features = ["full", "visit-mut"] }
unicode-general-category = "0.4.0"
