[package]
name = "gors"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
log = { version = "0.4", features = ["release_max_level_warn"] }
phf = { version = "0.10", features = ["macros"] }
pretty_env_logger = "0.4"
serde = "1.0.130"
serde_json = "1.0.68"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
