[package]
name = "go2rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.0.0-beta.5"
mimalloc = { version = "*", default-features = false }
phf = { version = "0.10", features = ["macros"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
