#![cfg(feature = "test_integration_generate")]
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use gors::test_support::fixtures_dir;
use sha2::Digest;
use std::path::Path;
use std::sync::Mutex;
use std::time::Instant;

static COMPILE_PROGRAM_MULTI_LOCK: Mutex<()> = Mutex::new(());

fn generated_prelude() -> &'static str {
    "//! Generated by gors. Do not edit.\n#![deny(dead_code, unused_imports, unused_macros, unsafe_code)]\n#![allow(nonstandard_style, private_interfaces, unreachable_code, unused_assignments, unused_mut, unused_parens, unused_variables)]\n\n"
}

fn write_fixture_file(path: &Path, source: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    std::fs::write(path, source).unwrap();
}

fn compile_temp_program(dir: &Path) -> gors::printer::GeneratedOutput {
    let program = gors::parser::parse_program(dir.to_str().unwrap()).unwrap();
    let compiled = compile_program_multi(program);
    gors::printer::generate_multi(compiled).unwrap()
}

fn compile_program_multi(program: gors::parser::ParsedProgram) -> gors::compiler::CompiledProgram {
    let verbose = std::env::var("GORS_TEST_VERBOSE")
        .map(|value| value == "1" || value.eq_ignore_ascii_case("true"))
        .unwrap_or(false);
    let test_name = std::thread::current()
        .name()
        .unwrap_or("test_integration_generate")
        .to_string();
    if verbose {
        eprintln!("[generate] {test_name}: waiting for compile_program_multi");
    }
    let _guard = COMPILE_PROGRAM_MULTI_LOCK
        .lock()
        .expect("generate integration compile lock should not be poisoned");
    let start = Instant::now();
    if verbose {
        eprintln!("[generate] {test_name}: compiling");
    }
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    if verbose {
        eprintln!("[generate] {test_name}: compiled in {:?}", start.elapsed());
    }
    compiled
}

#[test]
fn compile_multi_file_hello_world() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);
    assert!(compiled.has_main);
    assert!(compiled.modules.contains_key("__main__"));
    assert!(compiled.modules.contains_key("builtin"));
    assert!(compiled.modules.contains_key("fmt"));
}

#[test]
fn compile_multi_file_with_imports() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);

    assert!(compiled.has_main);
    assert!(compiled.modules.values().any(|m| m.mod_name == "greet"));
    assert!(compiled.modules.contains_key("builtin"));
    assert!(compiled.modules.contains_key("fmt"));

    let greet = compiled
        .modules
        .values()
        .find(|m| m.mod_name == "greet")
        .unwrap();
    assert_eq!(greet.filename, "example__greet.rs");
    assert!(!greet.content_hash.is_empty());
}

#[test]
fn generated_files_have_header_lints_and_blank_line() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);
    let output = gors::printer::generate_multi(compiled).unwrap();

    for (filename, source) in &output.files {
        assert!(
            source.starts_with(generated_prelude()),
            "{filename} should start with the generated gors header and lint prelude"
        );
    }
}

#[test]
fn generated_files_do_not_allow_dead_code() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);
    let output = gors::printer::generate_multi(compiled).unwrap();

    for (filename, source) in &output.files {
        assert!(
            !source.contains("allow(dead_code)"),
            "{filename} should not suppress generated dead code"
        );
    }
}

#[test]
fn generated_output_prunes_unreachable_items_and_builtin_helpers() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import "fmt"

const deadConst = 42

type deadStruct struct {
	value int
}

func deadLocal() {
	fmt.Println("dead")
}

func main() {
	fmt.Println("live")
}
"#,
    );

    let output = compile_temp_program(tmp.path());
    let main_rs = output.files.get("main.rs").unwrap();
    assert!(!main_rs.contains("deadConst"), "{main_rs}");
    assert!(!main_rs.contains("deadStruct"), "{main_rs}");
    assert!(!main_rs.contains("deadLocal"), "{main_rs}");

    let builtin_rs = output.files.get("builtin.rs").unwrap();
    assert!(!builtin_rs.contains("Chan"), "{builtin_rs}");
    assert!(!builtin_rs.contains("make_chan"), "{builtin_rs}");
}

#[test]
fn generated_output_prunes_unreferenced_imported_package_modules() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import (
	"example/dead"
	"example/live"
)

func main() {
	live.Hello()
}
"#,
    );
    write_fixture_file(
        tmp.path().join("dead/dead.go").as_path(),
        r#"
package dead

func Dead() {}
"#,
    );
    write_fixture_file(
        tmp.path().join("live/live.go").as_path(),
        r#"
package live

func Hello() {}
"#,
    );

    let output = compile_temp_program(tmp.path());
    assert!(output.files.contains_key("example__live.rs"));
    assert!(!output.files.contains_key("example__dead.rs"));
    assert!(
        !output
            .files
            .get("lib.rs")
            .unwrap()
            .contains("example__dead")
    );
}

#[test]
fn generated_output_prunes_lowered_away_errors_import() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import "errors"

func main() {
	_ = errors.New("boom")
}
"#,
    );

    let output = compile_temp_program(tmp.path());
    assert!(!output.files.contains_key("errors.rs"));
    assert!(!output.files.get("lib.rs").unwrap().contains("errors"));
}

#[test]
fn compile_multi_file_no_filename_collisions() {
    let path = fixtures_dir()
        .join("go_programs/import_recursive")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);

    let filenames: Vec<&str> = compiled
        .modules
        .values()
        .map(|m| m.filename.as_str())
        .collect();
    let unique: std::collections::HashSet<&str> = filenames.iter().copied().collect();
    assert_eq!(filenames.len(), unique.len(), "filenames must be unique");
}

#[test]
fn compile_multi_file_content_hash_stability() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();

    let program1 = gors::parser::parse_program(&path).unwrap();
    let compiled1 = compile_program_multi(program1);

    let program2 = gors::parser::parse_program(&path).unwrap();
    let compiled2 = compile_program_multi(program2);

    for (key, m1) in &compiled1.modules {
        if m1.is_stdlib {
            continue;
        }
        let m2 = compiled2.modules.get(key).unwrap();
        assert_eq!(
            m1.content_hash, m2.content_hash,
            "hash for {key} should be stable"
        );
    }
}

#[test]
fn compile_build_manifest_skip_unchanged() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();

    let tmp = tempfile::tempdir().unwrap();

    // First build
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);
    let output = gors::printer::generate_multi(compiled).unwrap();

    let mut manifest = gors::compiler::manifest::BuildManifest::new();
    for (filename, source) in &output.files {
        std::fs::write(tmp.path().join(filename), source).unwrap();
        manifest.modules.insert(
            filename.clone(),
            gors::compiler::manifest::ModuleEntry {
                content_hash: sha2::Sha256::digest(source.as_bytes())
                    .iter()
                    .map(|b| format!("{b:02x}"))
                    .collect::<String>(),
                output_file: filename.clone(),
            },
        );
    }
    manifest.save(tmp.path()).unwrap();

    // Load manifest and verify skip logic
    let loaded = gors::compiler::manifest::BuildManifest::load(tmp.path()).unwrap();
    for (filename, source) in &output.files {
        if filename == "lib.rs" || filename == "main.rs" {
            continue;
        }
        let digest = sha2::Sha256::digest(source.as_bytes());
        let hash = digest
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>();
        assert!(
            !loaded.needs_recompile(filename, &hash),
            "unchanged module {filename} should not need recompile"
        );
    }

    // A changed hash should trigger recompile
    assert!(loaded.needs_recompile("fmt.rs", "different_hash"));
}

#[test]
fn compile_multi_file_lib_rs_is_consumable() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = compile_program_multi(program);
    let output = gors::printer::generate_multi(compiled).unwrap();

    assert!(
        output.files.contains_key("lib.rs"),
        "lib.rs should exist for library consumption"
    );
    let lib_rs = output.files.get("lib.rs").unwrap();
    assert!(
        lib_rs.contains("pub mod"),
        "lib.rs should have pub mod declarations"
    );
}

#[test]
fn compile_sourcemap() {
    let go_file = fixtures_dir().join("go_programs/hello_world/main.go");
    let go_source = std::fs::read_to_string(&go_file).unwrap();
    let ast = gors::parser::parse_file(go_file.to_str().unwrap(), &go_source).unwrap();
    let compiled =
        gors::compiler::compile_with_source_map(ast, go_file.to_str().unwrap(), &go_source)
            .unwrap();
    let rust_source = gors::printer::generate(compiled).unwrap();
    let source_map = gors::compiler::build_source_map(&rust_source);

    let mut buf = Vec::new();
    source_map.to_writer(&mut buf).unwrap();
    let parsed = sourcemap::SourceMap::from_reader(&buf[..]).unwrap();

    assert!(parsed.get_token_count() > 0, "Empty sourcemap");
    assert_eq!(parsed.get_source(0), go_file.to_str());
}

#[test]
fn compile_program_multi_retains_referenced_stdlib_imports() {
    let go_source = r#"package main

import "fmt"
import "errors"
import "strconv"

func main() {
	fmt.Println("hello")
	e := errors.New("fail")
	s := strconv.Itoa(42)
}
"#;
    let ast = gors::parser::parse_file("main.go", go_source).unwrap();
    let program = gors::parser::ParsedProgram {
        main_package: gors::parser::ParsedPackage {
            name: "main".to_string(),
            import_path: String::new(),
            ast,
            files: vec![("main.go".to_string(), go_source.to_string())],
        },
        imports: vec![],
        stdlib_imports: vec![
            "errors".to_string(),
            "fmt".to_string(),
            "strconv".to_string(),
        ],
    };
    let compiled = compile_program_multi(program);
    assert!(compiled.modules.contains_key("fmt"));
    assert!(compiled.modules.contains_key("strconv"));
    assert!(!compiled.modules.contains_key("errors"));
    let output = gors::printer::generate_multi(compiled).unwrap();
    assert!(output.files.contains_key("fmt.rs"));
    assert!(output.files.contains_key("strconv.rs"));
    assert!(!output.files.contains_key("errors.rs"));
    let lib_rs = output.files.get("lib.rs").unwrap();
    assert!(lib_rs.contains("pub mod fmt"));
    assert!(lib_rs.contains("pub mod strconv"));
    assert!(!lib_rs.contains("pub mod errors"));
}
