#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

mod common;

use common::{discover_program_dirs, fixtures_dir};
use sha2::Digest;
use std::collections::BTreeMap;
use std::path::Path;
use std::process::Command;

fn rustc_cmd(src: &str, out: &str) -> Command {
    let mut cmd = Command::new("rustc");
    cmd.args([
        src,
        "--edition=2024",
        "-o",
        out,
        "-D",
        "unused_imports",
        "-D",
        "unused_macros",
    ]);
    cmd
}

fn compiled_module(
    mod_name: &str,
    filename: &str,
    file: syn::File,
    is_main: bool,
) -> gors::compiler::CompiledModule {
    gors::compiler::CompiledModule {
        mod_name: mod_name.to_string(),
        import_path: mod_name.to_string(),
        file,
        filename: filename.to_string(),
        content_hash: String::new(),
        is_main,
        is_stdlib: false,
    }
}

fn generated_prelude() -> &'static str {
    "//! Generated by gors. Do not edit.\n#![deny(dead_code, unused_imports, unused_macros, unsafe_code)]\n#![allow(nonstandard_style)]\n\n"
}

fn write_fixture_file(path: &Path, source: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    std::fs::write(path, source).unwrap();
}

fn compile_temp_program(dir: &Path) -> gors::backend_rust::GeneratedOutput {
    let program = gors::parser::parse_program(dir.to_str().unwrap()).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    gors::backend_rust::generate_multi(compiled).unwrap()
}

#[test]
fn generated_output_orders_macro_rules_before_invocations() {
    let file: syn::File = syn::parse_quote! {
        impl_real_complex_conversions!(i32);

        macro_rules! impl_real_complex_conversions {
            ($($ty:ty),*) => {};
        }
    };
    let source = gors::backend_rust::generate(file).unwrap();
    let definition = source
        .find("macro_rules! impl_real_complex_conversions")
        .unwrap();
    let invocation = source.find("impl_real_complex_conversions!(i32);").unwrap();

    assert!(definition < invocation, "{source}");
}

#[test]
fn compile_multi_file_hello_world() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    assert!(compiled.has_main);
    assert!(compiled.modules.contains_key("__main__"));
    assert!(compiled.modules.contains_key("builtin"));
    assert!(!compiled.modules.contains_key("fmt"));
}

#[test]
fn compile_multi_file_with_imports() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();

    assert!(compiled.has_main);
    assert!(compiled.modules.values().any(|m| m.mod_name == "greet"));
    assert!(compiled.modules.contains_key("builtin"));
    assert!(!compiled.modules.contains_key("fmt"));

    let greet = compiled
        .modules
        .values()
        .find(|m| m.mod_name == "greet")
        .unwrap();
    assert_eq!(greet.filename, "example__greet.rs");
    assert!(!greet.content_hash.is_empty());
}

#[test]
fn compile_multi_file_generate_and_compile() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    let output = gors::backend_rust::generate_multi(compiled).unwrap();

    let tmp = tempfile::tempdir().unwrap();
    for (filename, source) in &output.files {
        std::fs::write(tmp.path().join(filename), source).unwrap();
    }

    let main_rs = tmp.path().join("main.rs");
    let bin = tmp.path().join("main");
    let status = rustc_cmd(main_rs.to_str().unwrap(), bin.to_str().unwrap())
        .status()
        .unwrap();
    assert!(status.success(), "rustc compilation failed");

    let run_output = Command::new(&bin).output().unwrap();
    assert!(run_output.status.success());
    let stdout = String::from_utf8_lossy(&run_output.stdout);
    assert_eq!(stdout, "Hello from greet!\nGoodbye from greet!\n");
}

#[test]
fn generated_files_have_header_lints_and_blank_line() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    let output = gors::backend_rust::generate_multi(compiled).unwrap();

    for (filename, source) in &output.files {
        assert!(
            source.starts_with(generated_prelude()),
            "{filename} should start with the generated gors header and lint prelude"
        );
    }
}

#[test]
fn generated_files_do_not_allow_dead_code() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    let output = gors::backend_rust::generate_multi(compiled).unwrap();

    for (filename, source) in &output.files {
        assert!(
            !source.contains("allow(dead_code)"),
            "{filename} should not suppress generated dead code"
        );
    }
}

#[test]
fn generated_output_prunes_unreachable_items_and_builtin_helpers() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import "fmt"

const deadConst = 42

type deadStruct struct {
	value int
}

func deadLocal() {
	fmt.Println("dead")
}

func main() {
	fmt.Println("live")
}
"#,
    );

    let output = compile_temp_program(tmp.path());
    let main_rs = output.files.get("main.rs").unwrap();
    assert!(!main_rs.contains("deadConst"), "{main_rs}");
    assert!(!main_rs.contains("deadStruct"), "{main_rs}");
    assert!(!main_rs.contains("deadLocal"), "{main_rs}");

    let builtin_rs = output.files.get("builtin.rs").unwrap();
    assert!(!builtin_rs.contains("GoChan"), "{builtin_rs}");
    assert!(!builtin_rs.contains("make_chan"), "{builtin_rs}");
}

#[test]
fn generated_output_prunes_unreferenced_imported_package_modules() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import (
	"example/dead"
	"example/live"
)

func main() {
	live.Hello()
}
"#,
    );
    write_fixture_file(
        tmp.path().join("dead/dead.go").as_path(),
        r#"
package dead

func Dead() {}
"#,
    );
    write_fixture_file(
        tmp.path().join("live/live.go").as_path(),
        r#"
package live

func Hello() {}
"#,
    );

    let output = compile_temp_program(tmp.path());
    assert!(output.files.contains_key("example__live.rs"));
    assert!(!output.files.contains_key("example__dead.rs"));
    assert!(
        !output
            .files
            .get("lib.rs")
            .unwrap()
            .contains("example__dead")
    );
}

#[test]
fn generated_output_prunes_lowered_away_errors_import() {
    let tmp = tempfile::tempdir().unwrap();
    write_fixture_file(tmp.path().join("go.mod").as_path(), "module example\n");
    write_fixture_file(
        tmp.path().join("main.go").as_path(),
        r#"
package main

import "errors"

func main() {
	_ = errors.New("boom")
}
"#,
    );

    let output = compile_temp_program(tmp.path());
    assert!(!output.files.contains_key("errors.rs"));
    assert!(!output.files.get("lib.rs").unwrap().contains("errors"));
}

#[test]
fn generated_modules_and_methods_are_ordered() {
    let mut modules = BTreeMap::new();
    modules.insert(
        "__main__".to_string(),
        compiled_module(
            "main",
            "main.rs",
            syn::parse_quote! {
                pub fn main() {}
            },
            true,
        ),
    );
    modules.insert(
        "z".to_string(),
        compiled_module(
            "zeta",
            "zeta.rs",
            syn::parse_quote! {
                fn private_z() {}
            },
            false,
        ),
    );
    modules.insert(
        "a".to_string(),
        compiled_module(
            "alpha",
            "alpha.rs",
            syn::parse_quote! {
                fn private_alpha() {}
                pub fn PublicAlpha() {}
            },
            false,
        ),
    );
    let program = gors::compiler::CompiledProgram {
        modules,
        has_main: true,
    };

    let multi = gors::backend_rust::generate_multi(program.clone()).unwrap();
    let lib_rs = multi.files.get("lib.rs").unwrap();
    assert!(lib_rs.find("pub mod alpha;").unwrap() < lib_rs.find("pub mod zeta;").unwrap());
    let alpha_rs = multi.files.get("alpha.rs").unwrap();
    assert!(
        alpha_rs.find("pub fn PublicAlpha").unwrap() < alpha_rs.find("fn private_alpha").unwrap()
    );

    let single = gors::backend_rust::generate_single(program).unwrap();
    assert!(single.find("mod alpha").unwrap() < single.find("mod zeta").unwrap());
}

#[test]
fn compile_multi_file_no_filename_collisions() {
    let path = fixtures_dir()
        .join("go_programs/import_recursive")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();

    let filenames: Vec<&str> = compiled
        .modules
        .values()
        .map(|m| m.filename.as_str())
        .collect();
    let unique: std::collections::HashSet<&str> = filenames.iter().copied().collect();
    assert_eq!(filenames.len(), unique.len(), "filenames must be unique");
}

#[test]
fn compile_multi_file_content_hash_stability() {
    let path = fixtures_dir()
        .join("go_programs/import_local_package")
        .to_string_lossy()
        .to_string();

    let program1 = gors::parser::parse_program(&path).unwrap();
    let compiled1 = gors::compiler::compile_program_multi(program1).unwrap();

    let program2 = gors::parser::parse_program(&path).unwrap();
    let compiled2 = gors::compiler::compile_program_multi(program2).unwrap();

    for (key, m1) in &compiled1.modules {
        if m1.is_stdlib {
            continue;
        }
        let m2 = compiled2.modules.get(key).unwrap();
        assert_eq!(
            m1.content_hash, m2.content_hash,
            "hash for {key} should be stable"
        );
    }
}

#[test]
fn compile_build_manifest_skip_unchanged() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();

    let tmp = tempfile::tempdir().unwrap();

    // First build
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    let output = gors::backend_rust::generate_multi(compiled).unwrap();

    let mut manifest = gors::compiler::manifest::BuildManifest::new();
    for (filename, source) in &output.files {
        std::fs::write(tmp.path().join(filename), source).unwrap();
        manifest.modules.insert(
            filename.clone(),
            gors::compiler::manifest::ModuleEntry {
                content_hash: sha2::Sha256::digest(source.as_bytes())
                    .iter()
                    .map(|b| format!("{b:02x}"))
                    .collect::<String>(),
                output_file: filename.clone(),
            },
        );
    }
    manifest.save(tmp.path()).unwrap();

    // Load manifest and verify skip logic
    let loaded = gors::compiler::manifest::BuildManifest::load(tmp.path()).unwrap();
    for (filename, source) in &output.files {
        if filename == "lib.rs" || filename == "main.rs" {
            continue;
        }
        let digest = sha2::Sha256::digest(source.as_bytes());
        let hash = digest
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>();
        assert!(
            !loaded.needs_recompile(filename, &hash),
            "unchanged module {filename} should not need recompile"
        );
    }

    // A changed hash should trigger recompile
    assert!(loaded.needs_recompile("fmt.rs", "different_hash"));
}

#[test]
fn compile_multi_file_lib_rs_is_consumable() {
    let path = fixtures_dir()
        .join("go_programs/hello_world/main.go")
        .to_string_lossy()
        .to_string();
    let program = gors::parser::parse_program(&path).unwrap();
    let compiled = gors::compiler::compile_program_multi(program).unwrap();
    let output = gors::backend_rust::generate_multi(compiled).unwrap();

    assert!(
        output.files.contains_key("lib.rs"),
        "lib.rs should exist for library consumption"
    );
    let lib_rs = output.files.get("lib.rs").unwrap();
    assert!(
        lib_rs.contains("pub mod"),
        "lib.rs should have pub mod declarations"
    );
}

#[test]
fn compile_sourcemap() {
    let dirs = discover_program_dirs();

    for dir in &dirs {
        let (ast, files) = match gors::parser::parse_path(dir.to_str().unwrap()) {
            Ok(result) => result,
            Err(_) => continue,
        };

        let (go_file, go_source) = match files.first() {
            Some((f, s)) => (f.as_str(), s.as_str()),
            None => continue,
        };

        let compiled = match gors::compiler::compile_with_source_map(ast, go_file, go_source) {
            Ok(compiled) => compiled,
            Err(_) => continue,
        };

        let rust_source = match gors::backend_rust::generate(compiled) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let source_map = gors::compiler::build_source_map(&rust_source);

        let mut buf = Vec::new();
        if source_map.to_writer(&mut buf).is_err() {
            continue;
        }

        let parsed = match sourcemap::SourceMap::from_reader(&buf[..]) {
            Ok(sm) => sm,
            Err(e) => panic!("Invalid sourcemap for {}: {}", go_file, e),
        };

        assert!(
            parsed.get_token_count() > 0,
            "Empty sourcemap for {}",
            go_file
        );
        assert_eq!(
            parsed.get_source(0),
            Some(go_file),
            "Source file mismatch for {}",
            go_file
        );
    }
}

#[test]
fn generate_multi_no_unused_code() {
    let dirs = discover_program_dirs();

    for dir in &dirs {
        let main_go = dir.join("main.go");
        if !main_go.exists() {
            continue;
        }

        let path = dir.to_string_lossy().to_string();
        let program = match gors::parser::parse_program(&path) {
            Ok(p) => p,
            Err(_) => continue,
        };

        let compiled = match gors::compiler::compile_program_multi(program) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let output = match gors::backend_rust::generate_multi(compiled) {
            Ok(o) => o,
            Err(_) => continue,
        };

        let tmp = tempfile::tempdir().unwrap();
        for (filename, source) in &output.files {
            std::fs::write(tmp.path().join(filename), source).unwrap();
        }

        let main_rs = tmp.path().join("main.rs");
        let bin = tmp.path().join("main");

        let baseline = Command::new("rustc")
            .args([
                main_rs.to_str().unwrap(),
                "--edition=2024",
                "-o",
                bin.to_str().unwrap(),
            ])
            .output()
            .unwrap();
        if !baseline.status.success() {
            continue;
        }

        let out = rustc_cmd(main_rs.to_str().unwrap(), bin.to_str().unwrap())
            .output()
            .unwrap();

        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(
            out.status.success(),
            "generate_multi output for {} failed:\n{}",
            dir.display(),
            stderr,
        );
    }
}

#[test]
fn generate_single_no_unused_code() {
    let dirs = discover_program_dirs();

    for dir in &dirs {
        let main_go = dir.join("main.go");
        if !main_go.exists() {
            continue;
        }

        let path = dir.to_string_lossy().to_string();
        let program = match gors::parser::parse_program(&path) {
            Ok(p) => p,
            Err(_) => continue,
        };

        let compiled = match gors::compiler::compile_program_multi(program) {
            Ok(c) => c,
            Err(_) => continue,
        };

        let source = match gors::backend_rust::generate_single(compiled) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let tmp = tempfile::tempdir().unwrap();
        let rs_path = tmp.path().join("main.rs");
        let bin = tmp.path().join("main");
        std::fs::write(&rs_path, &source).unwrap();

        // Skip programs with pre-existing compilation errors unrelated to
        // unused-code (e.g. type mismatches in generated code).
        let baseline = Command::new("rustc")
            .args([
                rs_path.to_str().unwrap(),
                "--edition=2024",
                "-o",
                bin.to_str().unwrap(),
            ])
            .output()
            .unwrap();
        if !baseline.status.success() {
            continue;
        }

        let out = rustc_cmd(rs_path.to_str().unwrap(), bin.to_str().unwrap())
            .output()
            .unwrap();

        let stderr = String::from_utf8_lossy(&out.stderr);
        assert!(
            out.status.success(),
            "generate_single output for {} failed:\n{}",
            dir.display(),
            stderr,
        );
    }
}
