//! Rust source printer.
//!
//! This module prints Rust source code from a `syn::File` AST.

use crate::profile::ProfileTimer;

/// Write formatted Rust source code to a writer.
///
/// # Arguments
///
/// * `w` - The writer to output the formatted code to
/// * `file` - The Rust AST to format
///
/// # Returns
///
/// Returns `Ok(())` on success, or an error if writing fails.
pub fn fprint<W: std::io::Write>(
    mut w: W,
    file: syn::File,
) -> Result<(), Box<dyn std::error::Error>> {
    let formatted = prettyplease::unparse(&file);

    for (i, line) in formatted.lines().enumerate() {
        if i > 0 && (line.starts_with("fn") || line.starts_with("pub fn")) {
            w.write_all(b"\n")?;
        }
        w.write_all(line.as_bytes())?;
        w.write_all(b"\n")?;
    }

    Ok(())
}

/// Generate formatted Rust source code as a String.
///
/// # Arguments
///
/// * `file` - The Rust AST to format
///
/// # Returns
///
/// Returns `Ok(String)` containing the formatted source code, or an error
/// if formatting fails.
///
/// # Example
///
/// ```
/// use gors::{parser, compiler, printer};
///
/// let go_source = "package main\n\nfunc main() {}";
/// let go_ast = parser::parse_file("example.go", go_source).unwrap();
/// let rust_ast = compiler::compile_file_to_rust_syntax(go_ast).unwrap();
/// let rust_source = printer::generate(rust_ast).unwrap();
/// ```
pub fn generate(file: syn::File) -> Result<String, Box<dyn std::error::Error>> {
    let mut output = Vec::new();
    fprint(&mut output, file)?;
    Ok(String::from_utf8(output)?)
}

const GENERATED_HEADER: &str = "//! Generated by gors. Do not edit.\n";
const GENERATED_LINTS: &str = "#![deny(dead_code, unused_imports, unused_macros, unsafe_code)]\n#![allow(nonstandard_style, private_interfaces, unreachable_code, unused_assignments, unused_mut, unused_parens, unused_variables)]";

fn generated_source(source: String) -> String {
    format!("{GENERATED_HEADER}{GENERATED_LINTS}\n\n{source}")
}

/// Deterministic generated files for one compiled program.
#[derive(Clone)]
pub struct GeneratedOutput {
    pub files: std::collections::BTreeMap<String, String>,
}

fn main_wrapper_module_name(dependency_mods: &[&str]) -> String {
    let mut name = "__gors_lib".to_string();
    while dependency_mods.contains(&name.as_str()) {
        name.push('_');
    }
    name
}

pub fn generate_multi(
    program: crate::compiler::CompiledProgram,
) -> Result<GeneratedOutput, Box<dyn std::error::Error>> {
    let timer = ProfileTimer::start("printer.formatting");
    let mut files = std::collections::BTreeMap::new();
    let mut module_sources = std::collections::BTreeMap::new();

    if program
        .modules
        .contains_key(crate::artifact::RUNTIME_MODULE_NAME)
    {
        return Err(std::io::Error::other(format!(
            "generated module name {} is reserved for the runtime ABI",
            crate::artifact::RUNTIME_MODULE_NAME
        ))
        .into());
    }

    module_sources.insert(
        crate::artifact::RUNTIME_MODULE_NAME.to_string(),
        generated_source(crate::artifact::RUNTIME_SOURCE.to_string()),
    );

    for (module_name, file) in &program.modules {
        module_sources.insert(
            module_name.clone(),
            generated_source(generate(file.clone())?),
        );
    }
    let mod_decls = module_sources
        .keys()
        .map(|module_name| format!("pub mod {module_name};"))
        .collect::<Vec<_>>();
    for (module_name, source) in module_sources {
        files.insert(format!("{module_name}.rs"), source);
    }

    files.insert(
        "lib.rs".to_string(),
        generated_source(mod_decls.join("\n") + "\n"),
    );

    let mut main_parts = Vec::new();
    let dependency_mods = std::iter::once(crate::artifact::RUNTIME_MODULE_NAME)
        .chain(program.modules.keys().map(String::as_str))
        .collect::<Vec<_>>();
    let wrapper_mod = main_wrapper_module_name(&dependency_mods);
    main_parts.push(format!(
        "#[path = \"lib.rs\"]\nmod {wrapper_mod};\nuse {wrapper_mod}::*;",
    ));
    main_parts.push(generate(program.entry)?);
    files.insert(
        "main.rs".to_string(),
        generated_source(main_parts.join("\n\n") + "\n"),
    );

    drop(timer);
    Ok(GeneratedOutput { files })
}

/// Generate a single Rust source file from a compiled program.
///
/// The entry unit is emitted first. Dependency modules follow in deterministic
/// module-name order as inline `mod` blocks.
pub fn generate_single(
    program: crate::compiler::CompiledProgram,
) -> Result<String, Box<dyn std::error::Error>> {
    if program
        .modules
        .contains_key(crate::artifact::RUNTIME_MODULE_NAME)
    {
        return Err(std::io::Error::other(format!(
            "generated module name {} is reserved for the runtime ABI",
            crate::artifact::RUNTIME_MODULE_NAME
        ))
        .into());
    }
    let mut parts: Vec<String> = Vec::new();

    parts.push(generate(program.entry)?);
    parts.push(format!(
        "mod {} {{\n{}}}",
        crate::artifact::RUNTIME_MODULE_NAME,
        indent_block(crate::artifact::RUNTIME_SOURCE)
    ));

    // Dependency modules follow in deterministic module-name order.
    for (module_name, file) in program.modules {
        let body = generate(file)?;
        parts.push(format!("mod {module_name} {{\n{}}}", indent_block(&body)));
    }

    Ok(generated_source(parts.join("\n\n") + "\n"))
}

fn indent_block(source: &str) -> String {
    let mut out = String::with_capacity(source.len() + source.lines().count() * 4);
    for line in source.lines() {
        if !line.is_empty() {
            out.push_str("    ");
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

#[cfg(test)]
#[allow(clippy::panic, clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use std::collections::BTreeMap;
    use std::process::Command;

    use crate::compiler::input::{
        PackageInputManifest, PackageKey, ProgramInput, SourceFileInput, WorkspaceKey,
    };

    fn program(filename: &str, source: &str) -> ProgramInput {
        let package = PackageKey::command_line();
        let file = SourceFileInput::from_source(filename, filename, source).unwrap();
        let manifest = PackageInputManifest::new(package.clone(), [file]).unwrap();
        ProgramInput::new(
            WorkspaceKey::ad_hoc("printer-tests").unwrap(),
            package,
            [manifest],
        )
        .unwrap()
    }

    #[test]
    fn source_map_plan_maps_terminal_output() {
        let go_source = "package main\n\nfunc main() {}\n";
        let (compiled, source_map_plan) =
            crate::compiler::compile_program_with_source_map(program("test.go", go_source))
                .unwrap();
        let rust_source = super::generate_single(compiled).unwrap();
        let source_map = source_map_plan.build(&rust_source);

        assert!(rust_source.contains("fn main"), "{rust_source}");
        assert!(source_map.get_token_count() > 0);
        assert_eq!(source_map.get_source(0), Some("test.go"));
        let names = (0..source_map.get_name_count())
            .filter_map(|idx| source_map.get_name(idx))
            .collect::<Vec<_>>();
        assert_eq!(names, vec!["main"]);
    }

    #[test]
    fn printer_preserves_terminal_emitter_order() {
        let file: syn::File = syn::parse_quote! {
            impl_real_complex_conversions!(i32);

            macro_rules! impl_real_complex_conversions {
                ($($ty:ty),*) => {};
            }
        };
        let source = super::generate(file).unwrap();
        let definition = source
            .find("macro_rules! impl_real_complex_conversions")
            .unwrap();
        let invocation = source.find("impl_real_complex_conversions!(i32);").unwrap();

        assert!(invocation < definition, "{source}");
    }

    #[test]
    fn generated_modules_and_methods_are_ordered() {
        let mut modules = BTreeMap::new();
        modules.insert(
            "zeta".to_string(),
            syn::parse_quote! {
                fn private_z() {}
            },
        );
        modules.insert(
            "alpha".to_string(),
            syn::parse_quote! {
                fn private_alpha() {}
                pub fn PublicAlpha() {}
            },
        );
        let program = crate::compiler::CompiledProgram {
            entry: syn::parse_quote! { pub fn main() {} },
            modules,
        };

        let multi = super::generate_multi(program.clone()).unwrap();
        let lib_rs = multi.files.get("lib.rs").unwrap();
        assert!(lib_rs.find("pub mod alpha;").unwrap() < lib_rs.find("pub mod zeta;").unwrap());
        let alpha_rs = multi.files.get("alpha.rs").unwrap();
        assert!(
            alpha_rs.find("fn private_alpha").unwrap()
                < alpha_rs.find("pub fn PublicAlpha").unwrap()
        );

        let single = super::generate_single(program).unwrap();
        assert!(single.find("mod alpha").unwrap() < single.find("mod zeta").unwrap());
    }

    #[test]
    fn generated_multi_files_have_header_lints_and_blank_line() {
        let mut modules = BTreeMap::new();
        modules.insert(
            "dependency".to_string(),
            syn::parse_quote! {
                pub fn Used() {}
            },
        );
        let program = crate::compiler::CompiledProgram {
            entry: syn::parse_quote! { pub fn main() {} },
            modules,
        };
        let output = super::generate_multi(program).unwrap();
        let expected_prefix = format!("{}{}\n\n", super::GENERATED_HEADER, super::GENERATED_LINTS);

        for (filename, source) in &output.files {
            assert!(
                source.starts_with(&expected_prefix),
                "{filename} should start with the generated header and lint prelude"
            );
            if filename == "__gors_runtime.rs" {
                assert!(source.contains("allow(dead_code)"));
            } else {
                assert!(
                    !source.contains("allow(dead_code)"),
                    "{filename} should keep dead-code denial enabled"
                );
            }
        }
    }

    #[test]
    fn runtime_program_compiles_in_multi_and_single_layouts() {
        let source = "package main\nfunc join(left string, right string) string { return left + right }\nfunc main() { println(join(\"\\xff\", \"\\x00\")) }\n";
        let compiled = crate::compiler::compile_program(program("main.go", source)).unwrap();
        let temporary = tempfile::tempdir().unwrap();
        let expected = [0xff, 0, b'\n'];

        let multi_dir = temporary.path().join("multi");
        std::fs::create_dir(&multi_dir).unwrap();
        for (filename, source) in super::generate_multi(compiled.clone()).unwrap().files {
            std::fs::write(multi_dir.join(filename), source).unwrap();
        }
        compile_and_assert_output(
            &multi_dir.join("main.rs"),
            &multi_dir.join("main"),
            &expected,
        );

        let single_source = super::generate_single(compiled).unwrap();
        let single_path = temporary.path().join("single.rs");
        let single_binary = temporary.path().join("single");
        std::fs::write(&single_path, single_source).unwrap();
        compile_and_assert_output(&single_path, &single_binary, &expected);
    }

    fn compile_and_assert_output(
        source: &std::path::Path,
        binary: &std::path::Path,
        expected_stderr: &[u8],
    ) {
        let compilation = Command::new("rustc")
            .arg("--edition=2024")
            .arg(source)
            .arg("-o")
            .arg(binary)
            .output()
            .unwrap();
        assert!(
            compilation.status.success(),
            "{}",
            String::from_utf8_lossy(&compilation.stderr)
        );

        let execution = Command::new(binary).output().unwrap();
        assert!(execution.status.success(), "{execution:?}");
        assert!(execution.stdout.is_empty(), "{execution:?}");
        assert_eq!(execution.stderr, expected_stderr);
    }
}
