// wasm-pack's bundler entry asks webpack to instantiate the 20MB compiler wasm
// as a top-level async module. In Chromium workers that path can stall before
// the worker's message handler is installed, so instantiate the wasm asset
// explicitly and then attach it to the generated JS glue.
// @ts-expect-error gors_bg.js is generated by wasm-bindgen and has no d.ts.
import * as bindings from "./wasm/pkg/gors_bg.js";

export interface GorsBuildResult {
	readonly success: boolean;
	readonly output: string;
	readonly error_message: string;
	readonly error_line: number;
	readonly error_column: number;
	readonly error_end_column: number;
	readonly error_kind: string;
	get_mappings_json(): string;
	mapping_count(): number;
	free(): void;
}

type WasmBindings = {
	build_rust(input: string): GorsBuildResult;
	__wbg_set_wasm(exports: WebAssembly.Exports): void;
};

type StartableExports = WebAssembly.Exports & {
	__wbindgen_start?: () => void;
};

const wasmBindings = bindings as WasmBindings;
let initPromise: Promise<WasmBindings> | null = null;

function importObject(): WebAssembly.Imports {
	return {
		"./gors_bg.js": bindings as Record<string, WebAssembly.ImportValue>,
	};
}

async function instantiateWasm(): Promise<StartableExports> {
	const wasmUrl = new URL("./wasm/pkg/gors_bg.wasm", import.meta.url);
	const response = await fetch(wasmUrl);
	const imports = importObject();

	if (
		typeof WebAssembly.instantiateStreaming === "function" &&
		response.headers.get("Content-Type") === "application/wasm"
	) {
		const { instance } = await WebAssembly.instantiateStreaming(
			response,
			imports,
		);
		return instance.exports;
	}

	const bytes = await response.arrayBuffer();
	const { instance } = await WebAssembly.instantiate(bytes, imports);
	return instance.exports;
}

export function loadGorsWasm(): Promise<WasmBindings> {
	initPromise ??= instantiateWasm().then((exports) => {
		wasmBindings.__wbg_set_wasm(exports);
		exports.__wbindgen_start?.();
		return wasmBindings;
	});
	return initPromise;
}
