//! Stable identities for runtime operations.

use super::RuntimeOp;

/// Stable compact identity of one runtime ABI operation.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RuntimeOpId(pub(super) u16);

/// Stable operation ID that is not defined by this ABI crate.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct UnknownRuntimeOpId(pub(super) u16);

impl RuntimeOp {
    /// Stable compact identity for canonical encodings and fingerprints.
    #[must_use]
    pub const fn id(self) -> RuntimeOpId {
        RuntimeOpId(match self {
            Self::GoStringFromBytes => 1,
            Self::GoStringFromStatic => 2,
            Self::ConcatGoStrings => 3,
            Self::Integer { op, kind } => op.runtime_id(kind),
            Self::PrintBool => 13,
            Self::PrintI64 => 14,
            Self::PrintSpace => 15,
            Self::PrintNewline => 16,
            Self::PrintGoString => 17,
            Self::PanicBool => 18,
            Self::PanicI64 => 19,
            Self::PanicGoString => 20,
            Self::GoSliceI64FromStatic => 21,
            Self::GoSliceI64Index => 22,
            Self::GoSliceI64Range => 23,
            Self::GoSliceI64Set => 24,
            Self::GoSliceI64Make => 25,
            Self::GoSliceI64Len => 26,
            Self::GoSliceI64Cap => 27,
            Self::GoSliceI64Append => 28,
            Self::GoSliceU8FromStatic => 29,
            Self::GoSliceU8AppendSlice => 30,
            Self::GoSliceU8AppendString => 31,
            Self::GoSliceU8CopyString => 32,
            Self::GoSliceI64Clear => 33,
            Self::GoStringFromSliceU8 => 34,
            Self::GoSliceI64Copy => 35,
            Self::GoMapStringI64Nil => 36,
            Self::GoMapStringI64Make => 37,
            Self::GoMapStringI64Len => 38,
            Self::GoMapStringI64Get => 39,
            Self::GoMapStringI64Contains => 40,
            Self::GoMapStringI64Set => 41,
            Self::GoMapStringI64Delete => 42,
            Self::GoMapStringI64Clear => 43,
            Self::GoMapStringI64IsNil => 44,
            Self::GoMapStringI64KeyAt => 45,
            Self::GoPointerI64Nil => 46,
            Self::GoPointerI64New => 47,
            Self::GoPointerI64Get => 48,
            Self::GoPointerI64Set => 49,
            Self::GoPointerI64IsNil => 50,
            Self::GoChannelI64Nil => 51,
            Self::GoChannelI64Make => 52,
            Self::GoChannelI64Len => 53,
            Self::GoChannelI64Cap => 54,
            Self::GoChannelI64Send => 55,
            Self::GoChannelI64ReceiveValue => 56,
            Self::GoChannelI64Receive => 57,
            Self::GoChannelI64Close => 58,
            Self::GoChannelI64IsNil => 59,
            Self::GoStringLen => 60,
            Self::GoChannelI64TrySend => 61,
            Self::GoChannelI64TryReceive => 62,
            Self::GoPointerStructI64Nil => 63,
            Self::GoPointerStructI64New => 64,
            Self::GoPointerStructI64Get => 65,
            Self::GoPointerStructI64Set => 66,
            Self::GoPointerStructI64IsNil => 67,
            Self::GoPointerStructI64Equal => 68,
            Self::GoInterfaceNil => 69,
            Self::GoInterfaceBoxBool => 70,
            Self::GoInterfaceBoxI64 => 71,
            Self::GoInterfaceBoxGoString => 72,
            Self::GoInterfaceBoxStructI64 => 73,
            Self::GoInterfaceBoxPointerStructI64 => 74,
            Self::GoInterfaceIsNil => 75,
            Self::GoInterfaceIsType => 76,
            Self::GoInterfaceUnboxBool => 77,
            Self::GoInterfaceUnboxI64 => 78,
            Self::GoInterfaceUnboxGoString => 79,
            Self::GoInterfaceStructI64Get => 80,
            Self::GoInterfaceUnboxPointerStructI64 => 81,
            Self::GoSliceBoolFromStatic => 82,
            Self::GoSliceBoolIndex => 83,
            Self::GoSliceBoolSet => 84,
            Self::GoSliceInterfaceMake => 85,
            Self::GoSliceInterfaceLen => 86,
            Self::GoSliceInterfaceIndex => 87,
            Self::GoSliceInterfaceSet => 88,
            Self::GoMapStringInterfaceMake => 89,
            Self::GoMapStringInterfaceLen => 90,
            Self::GoMapStringInterfaceGet => 91,
            Self::GoMapStringInterfaceContains => 92,
            Self::GoMapStringInterfaceSet => 93,
            Self::GoSliceU8Len => 94,
            Self::GoSliceU8Index => 95,
            Self::GoSliceU8Range => 96,
            Self::GoStringIndex => 97,
            Self::GoStringRange => 98,
            Self::GoStringFromSliceRunes => 99,
            Self::GoStringRangeCount => 100,
            Self::GoStringRangeIndexAt => 101,
            Self::GoStringRangeRuneAt => 102,
            Self::GoSliceI64Nil => 103,
            Self::GoSliceI64IsNil => 104,
            Self::GoSliceU8Nil => 105,
            Self::GoSliceU8IsNil => 106,
            Self::GoSliceBoolNil => 107,
            Self::GoSliceBoolIsNil => 108,
            Self::GoSliceInterfaceNil => 109,
            Self::GoSliceInterfaceIsNil => 110,
            Self::GoInterfaceBoxAggregate => 111,
            Self::GoInterfaceUnboxAggregate => 112,
            Self::GoSliceU8Make => 113,
            Self::GoSliceU8Set => 114,
            Self::GoSliceU8Copy => 115,
            Self::PrintF64 => 116,
            Self::GoInterfaceBoxF64 => 117,
            Self::GoInterfaceUnboxF64 => 118,
            Self::GoInterfaceEqual => 119,
            Self::GoInterfaceBoxComparableAggregate => 120,
            Self::GoStringFromRune => 121,
            Self::PanicGoInterface => 122,
            Self::GoPanicPayloadToInterface => 123,
            Self::GoInterfaceIsRuntimeError => 124,
            Self::GoChannelGoStringNil => 125,
            Self::GoChannelGoStringMake => 126,
            Self::GoChannelGoStringLen => 127,
            Self::GoChannelGoStringCap => 128,
            Self::GoChannelGoStringSend => 129,
            Self::GoChannelGoStringReceiveValue => 130,
            Self::GoChannelGoStringReceive => 131,
            Self::GoChannelGoStringClose => 132,
            Self::GoChannelGoStringIsNil => 133,
            Self::GoChannelGoStringTrySend => 134,
            Self::GoChannelGoStringTryReceive => 135,
            Self::GoChannelGoChannelI64Nil => 136,
            Self::GoChannelGoChannelI64Make => 137,
            Self::GoChannelGoChannelI64Len => 138,
            Self::GoChannelGoChannelI64Cap => 139,
            Self::GoChannelGoChannelI64Send => 140,
            Self::GoChannelGoChannelI64ReceiveValue => 141,
            Self::GoChannelGoChannelI64Receive => 142,
            Self::GoChannelGoChannelI64Close => 143,
            Self::GoChannelGoChannelI64IsNil => 144,
            Self::GoChannelGoChannelI64TrySend => 145,
            Self::GoChannelGoChannelI64TryReceive => 146,
            Self::GoSliceGoStringNil => 147,
            Self::GoSliceGoStringMake => 148,
            Self::GoSliceGoStringLen => 149,
            Self::GoSliceGoStringCap => 150,
            Self::GoSliceGoStringIndex => 151,
            Self::GoSliceGoStringRange => 152,
            Self::GoSliceGoStringSet => 153,
            Self::GoSliceGoStringAppend => 154,
            Self::GoSliceGoStringCopy => 155,
            Self::GoSliceGoStringClear => 156,
            Self::GoSliceGoStringIsNil => 157,
            Self::GoInterfaceBoxGoSliceGoString => 158,
            Self::GoInterfaceUnboxGoSliceGoString => 159,
            Self::PrintU64 => 160,
            Self::GoMapStringI64RangeKeys => 161,
            Self::GoMapI64GoStringNil => 162,
            Self::GoMapI64GoStringMake => 163,
            Self::GoMapI64GoStringLen => 164,
            Self::GoMapI64GoStringGet => 165,
            Self::GoMapI64GoStringContains => 166,
            Self::GoMapI64GoStringSet => 167,
            Self::GoMapI64GoStringDelete => 168,
            Self::GoMapI64GoStringClear => 169,
            Self::GoMapI64GoStringIsNil => 170,
            Self::GoMapI64GoStringRangeKeys => 171,
            Self::GoStringToSliceRunes => 216,
        })
    }
}
