[package]
name = "gors-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gors"
path = "main.rs"

[dependencies]
clap = "3.0.0-beta.5"
gors = { path = "../gors" }
pretty_env_logger = "0.4"
serde_json = "1.0.68"
tempdir = "0.3.7"
