[package]
name = "gors-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gors"
path = "main.rs"

[dependencies]
clap = { version = "3.0.0-rc.0", features = ["derive"] }
gors = { path = "../gors" }
pretty_env_logger = "0.4.0"
serde_json = "1.0.72"
tempdir = "0.3.7"
