// Generated by scripts/generate-conformance-report.mjs.
// Run `npm run generate:conformance-report` from www/ after editing tests/fixtures/conformance/spec.json.

export type SpecConformanceStatus = "passing" | "skipped";

export interface SpecConformanceSource {
	readonly title: string;
	readonly url: string;
	readonly languageVersion: string;
	readonly published: string;
	readonly retrieved: string;
}

export interface SpecConformanceTest {
	readonly id: string;
	readonly section: string;
	readonly title: string;
	readonly status: SpecConformanceStatus;
	readonly fixtures: readonly string[];
	readonly reason: string;
}

export interface SpecConformanceCategory {
	readonly name: string;
	readonly testCount: number;
	readonly passingTestCount: number;
	readonly skippedTestCount: number;
	readonly tests: readonly SpecConformanceTest[];
}

export const specConformanceSource: SpecConformanceSource = {
	"title": "The Go Programming Language Specification",
	"url": "https://go.dev/ref/spec",
	"languageVersion": "go1.26",
	"published": "2026-01-12",
	"retrieved": "2026-05-27"
};

export const specConformanceCategories: readonly SpecConformanceCategory[] = [
	{
		"name": "Source code representation",
		"testCount": 3,
		"passingTestCount": 0,
		"skippedTestCount": 3,
		"tests": [
			{
				"id": "source-unicode-text",
				"section": "Source code representation",
				"title": "Source text is UTF-8 Unicode and code points are distinct",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs explicit scanner/parser fixtures for non-ASCII identifiers and canonical-equivalent code points."
			},
			{
				"id": "source-nul-character",
				"section": "Source code representation",
				"title": "NUL character implementation restriction is diagnosed consistently",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs negative scanner diagnostics in the conformance harness."
			},
			{
				"id": "source-byte-order-mark",
				"section": "Source code representation",
				"title": "Leading UTF-8 byte order mark is accepted and later BOMs are rejected",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs byte-level source fixtures outside normal text-file handling."
			}
		]
	},
	{
		"name": "Lexical elements",
		"testCount": 13,
		"passingTestCount": 12,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "lexical-comments",
				"section": "Comments",
				"title": "Line and block comments are ignored outside literals",
				"status": "passing",
				"fixtures": [
					"hello_world"
				],
				"reason": ""
			},
			{
				"id": "lexical-semicolons",
				"section": "Semicolons",
				"title": "Automatic semicolon insertion accepts idiomatic newlines",
				"status": "passing",
				"fixtures": [
					"hello_world",
					"nested_if_else",
					"for_loop_example"
				],
				"reason": ""
			},
			{
				"id": "lexical-identifiers",
				"section": "Identifiers",
				"title": "Identifiers name variables, functions, packages, types, and fields",
				"status": "passing",
				"fixtures": [
					"var_declaration",
					"multiple_functions",
					"struct_methods"
				],
				"reason": ""
			},
			{
				"id": "lexical-keywords",
				"section": "Keywords",
				"title": "Reserved keywords parse in declarations and statements",
				"status": "passing",
				"fixtures": [
					"switch_basic",
					"select_break",
					"multiple_defer",
					"goroutine_channel"
				],
				"reason": ""
			},
			{
				"id": "lexical-operators-punctuation",
				"section": "Operators and punctuation",
				"title": "Operators and punctuation are tokenized with longest-match rules",
				"status": "passing",
				"fixtures": [
					"arithmetic_operators",
					"boolean_logic",
					"unary_operators"
				],
				"reason": ""
			},
			{
				"id": "lexical-integer-literals",
				"section": "Integer literals",
				"title": "Integer literals support decimal values and separators in executable code",
				"status": "passing",
				"fixtures": [
					"integer_overflow",
					"iota_expression"
				],
				"reason": ""
			},
			{
				"id": "lexical-integer-base-prefixes",
				"section": "Integer literals",
				"title": "Integer literals support binary, octal, and hexadecimal prefixes",
				"status": "passing",
				"fixtures": [
					"conformance_integer_base_literals"
				],
				"reason": ""
			},
			{
				"id": "lexical-floating-literals",
				"section": "Floating-point literals",
				"title": "Decimal floating-point literals compile and execute",
				"status": "passing",
				"fixtures": [
					"math_basic",
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "lexical-hex-floating-literals",
				"section": "Floating-point literals",
				"title": "Hexadecimal floating-point literals compile and execute",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs literal lowering because Rust syntax does not accept Go hexadecimal float forms directly."
			},
			{
				"id": "lexical-imaginary-literals",
				"section": "Imaginary literals",
				"title": "Imaginary literals lower to complex values",
				"status": "passing",
				"fixtures": [
					"imaginary_literals",
					"complex_types"
				],
				"reason": ""
			},
			{
				"id": "lexical-rune-literals",
				"section": "Rune literals",
				"title": "Rune literals and escapes lower to rune values",
				"status": "passing",
				"fixtures": [
					"rune_literals"
				],
				"reason": ""
			},
			{
				"id": "lexical-string-literals",
				"section": "String literals",
				"title": "Interpreted string literals and escapes preserve Go values",
				"status": "passing",
				"fixtures": [
					"string_language",
					"string_concat"
				],
				"reason": ""
			},
			{
				"id": "lexical-raw-string-literals",
				"section": "String literals",
				"title": "Raw string literals preserve content except carriage returns",
				"status": "passing",
				"fixtures": [
					"conformance_raw_string_literals"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Constants",
		"testCount": 6,
		"passingTestCount": 5,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "constants-boolean",
				"section": "Constants",
				"title": "Boolean constants participate in expressions",
				"status": "passing",
				"fixtures": [
					"boolean_logic"
				],
				"reason": ""
			},
			{
				"id": "constants-iota",
				"section": "Iota",
				"title": "iota increments across const specifications",
				"status": "passing",
				"fixtures": [
					"iota_basic",
					"iota_expression"
				],
				"reason": ""
			},
			{
				"id": "constants-string-concat",
				"section": "Constant expressions",
				"title": "String constant concatenation is evaluated",
				"status": "passing",
				"fixtures": [
					"string_concat"
				],
				"reason": ""
			},
			{
				"id": "constants-numeric-expressions",
				"section": "Constant expressions",
				"title": "Numeric constant expressions are folded and coerced at use sites",
				"status": "passing",
				"fixtures": [
					"global_const",
					"integer_overflow",
					"operator_precedence"
				],
				"reason": ""
			},
			{
				"id": "constants-representability",
				"section": "Representability",
				"title": "Untyped constants are checked for representability by target type",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs negative diagnostics for overflow and non-representable assignments."
			},
			{
				"id": "constants-complex",
				"section": "Constants",
				"title": "Complex constants preserve real and imaginary components",
				"status": "passing",
				"fixtures": [
					"complex_types",
					"gostdlib_builtin"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Variables and zero values",
		"testCount": 5,
		"passingTestCount": 5,
		"skippedTestCount": 0,
		"tests": [
			{
				"id": "vars-var-declarations",
				"section": "Variable declarations",
				"title": "var declarations with and without explicit types initialize correctly",
				"status": "passing",
				"fixtures": [
					"var_declaration",
					"package_var_typed"
				],
				"reason": ""
			},
			{
				"id": "vars-short-declarations",
				"section": "Short variable declarations",
				"title": "Short variable declarations infer types and values",
				"status": "passing",
				"fixtures": [
					"simple_add",
					"multiple_assignment"
				],
				"reason": ""
			},
			{
				"id": "vars-zero-values",
				"section": "The zero value",
				"title": "Default zero values are emitted for declared variables",
				"status": "passing",
				"fixtures": [
					"zero_values"
				],
				"reason": ""
			},
			{
				"id": "vars-blank-identifier",
				"section": "Blank identifier",
				"title": "Blank identifier discards values in declarations and assignments",
				"status": "passing",
				"fixtures": [
					"blank_identifier"
				],
				"reason": ""
			},
			{
				"id": "vars-addressability",
				"section": "Address operators",
				"title": "Addressable variables can be mutated through pointers",
				"status": "passing",
				"fixtures": [
					"pointer_basic",
					"pointer_deref_assign",
					"pointer_local_alias"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Types",
		"testCount": 17,
		"passingTestCount": 14,
		"skippedTestCount": 3,
		"tests": [
			{
				"id": "types-booleans",
				"section": "Boolean types",
				"title": "Boolean values lower to Rust bool behavior",
				"status": "passing",
				"fixtures": [
					"boolean_logic"
				],
				"reason": ""
			},
			{
				"id": "types-integers",
				"section": "Numeric types",
				"title": "Signed and unsigned integer operations execute",
				"status": "passing",
				"fixtures": [
					"arithmetic_operators",
					"integer_overflow"
				],
				"reason": ""
			},
			{
				"id": "types-floats",
				"section": "Numeric types",
				"title": "Floating-point operations execute",
				"status": "passing",
				"fixtures": [
					"math_basic",
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "types-complex",
				"section": "Numeric types",
				"title": "complex64 and complex128 values execute through builtin helpers",
				"status": "passing",
				"fixtures": [
					"complex_types",
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "types-strings",
				"section": "String types",
				"title": "Strings support indexing, slicing, concatenation, and conversion",
				"status": "passing",
				"fixtures": [
					"string_concat",
					"string_language",
					"range_string"
				],
				"reason": ""
			},
			{
				"id": "types-arrays",
				"section": "Array types",
				"title": "Arrays have fixed length and support indexed mutation",
				"status": "passing",
				"fixtures": [
					"named_array_index_assignment",
					"range_array_pointer"
				],
				"reason": ""
			},
			{
				"id": "types-slices",
				"section": "Slice types",
				"title": "Slices support len, cap, append, copy, and full-slice expressions",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin",
					"full_slice_expression"
				],
				"reason": ""
			},
			{
				"id": "types-slice-backing-array",
				"section": "Slice types",
				"title": "Slice expressions share the original backing array",
				"status": "skipped",
				"fixtures": [
					"conformance/slice_alias_mutation"
				],
				"reason": "Current lowering materializes Vec copies for ordinary slice expressions."
			},
			{
				"id": "types-structs",
				"section": "Struct types",
				"title": "Struct fields, methods, and embedding execute",
				"status": "passing",
				"fixtures": [
					"struct_methods",
					"struct_embedding",
					"struct_string_fields"
				],
				"reason": ""
			},
			{
				"id": "types-pointers",
				"section": "Pointer types",
				"title": "Pointers support nil checks, dereference, and assignment",
				"status": "passing",
				"fixtures": [
					"pointer_basic",
					"pointer_nil_comparison",
					"pointer_deref_assign"
				],
				"reason": ""
			},
			{
				"id": "types-functions",
				"section": "Function types",
				"title": "Function values and closures are callable",
				"status": "passing",
				"fixtures": [
					"function_values",
					"closure_return",
					"recursive_func_literal"
				],
				"reason": ""
			},
			{
				"id": "types-interfaces",
				"section": "Interface types",
				"title": "Interfaces dispatch methods and support assertions",
				"status": "passing",
				"fixtures": [
					"interface_methods",
					"interface_type_assertion",
					"interface_return"
				],
				"reason": ""
			},
			{
				"id": "types-interface-method-sets",
				"section": "Method sets",
				"title": "Interface method sets match pointer and value receiver rules",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs method-set fixtures that distinguish pointer-only and value receiver assignability."
			},
			{
				"id": "types-maps",
				"section": "Map types",
				"title": "Maps support literal construction, indexing, mutation, and comma-ok",
				"status": "passing",
				"fixtures": [
					"map_comma_ok",
					"map_index_inc_dec",
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "types-channels",
				"section": "Channel types",
				"title": "Channels support send, receive, buffering, close, and comma-ok",
				"status": "passing",
				"fixtures": [
					"channel_basic",
					"channel_buffered",
					"channel_comma_ok"
				],
				"reason": ""
			},
			{
				"id": "types-aliases",
				"section": "Alias declarations",
				"title": "Alias declarations preserve underlying behavior",
				"status": "passing",
				"fixtures": [
					"var_alias_from_later_static"
				],
				"reason": ""
			},
			{
				"id": "types-recursive",
				"section": "Type declarations",
				"title": "Recursive named types compile and execute",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs fixtures for self-referential structs, interfaces, and pointer cycles."
			}
		]
	},
	{
		"name": "Properties of types and values",
		"testCount": 4,
		"passingTestCount": 3,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "properties-assignability",
				"section": "Assignability",
				"title": "Values assign to variables with compatible types",
				"status": "passing",
				"fixtures": [
					"any_assignment",
					"multiple_assignment",
					"interface_downcast"
				],
				"reason": ""
			},
			{
				"id": "properties-comparability",
				"section": "Comparison operators",
				"title": "Comparable values participate in equality and ordering",
				"status": "passing",
				"fixtures": [
					"boolean_logic",
					"arithmetic_operators",
					"string_language"
				],
				"reason": ""
			},
			{
				"id": "properties-non-comparable",
				"section": "Comparison operators",
				"title": "Non-comparable values are rejected by comparison and map-key contexts",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs negative semantic diagnostics for slices, maps, and functions."
			},
			{
				"id": "properties-method-sets",
				"section": "Method sets",
				"title": "Method expressions and method values preserve receiver semantics",
				"status": "passing",
				"fixtures": [
					"method_expression",
					"struct_methods",
					"generic_type_method"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Declarations and scope",
		"testCount": 9,
		"passingTestCount": 9,
		"skippedTestCount": 0,
		"tests": [
			{
				"id": "decl-package-clause",
				"section": "Package clause",
				"title": "Package clauses define package-level compilation units",
				"status": "passing",
				"fixtures": [
					"hello_world",
					"multi_file_same_package"
				],
				"reason": ""
			},
			{
				"id": "decl-imports",
				"section": "Import declarations",
				"title": "Imports resolve local, nested, multi-file, and recursive packages",
				"status": "passing",
				"fixtures": [
					"import_local_package",
					"import_nested_package",
					"import_recursive"
				],
				"reason": ""
			},
			{
				"id": "decl-const",
				"section": "Constant declarations",
				"title": "const declarations define package and local constants",
				"status": "passing",
				"fixtures": [
					"global_const",
					"iota_basic",
					"iota_expression"
				],
				"reason": ""
			},
			{
				"id": "decl-type",
				"section": "Type declarations",
				"title": "type declarations define structs, aliases, interfaces, and generic types",
				"status": "passing",
				"fixtures": [
					"struct_methods",
					"interface_methods",
					"generic_type_method"
				],
				"reason": ""
			},
			{
				"id": "decl-var",
				"section": "Variable declarations",
				"title": "var declarations work at package and block scope",
				"status": "passing",
				"fixtures": [
					"var_declaration",
					"package_var_typed",
					"nested_scope_shadowing"
				],
				"reason": ""
			},
			{
				"id": "decl-functions",
				"section": "Function declarations",
				"title": "Functions support parameters, returns, recursion, and shorthand parameter lists",
				"status": "passing",
				"fixtures": [
					"multiple_functions",
					"multi_return",
					"function_signature_shorthand",
					"mutual_recursion"
				],
				"reason": ""
			},
			{
				"id": "decl-methods",
				"section": "Method declarations",
				"title": "Methods attach to named receiver types",
				"status": "passing",
				"fixtures": [
					"struct_methods",
					"variadic_method",
					"generic_type_method"
				],
				"reason": ""
			},
			{
				"id": "decl-scope-shadowing",
				"section": "Declarations and scope",
				"title": "Nested scopes and shadowing follow Go name resolution",
				"status": "passing",
				"fixtures": [
					"scope_shadowing",
					"nested_scope_shadowing",
					"closure_shadowing"
				],
				"reason": ""
			},
			{
				"id": "decl-init",
				"section": "Program initialization and execution",
				"title": "init functions run before main after package variable initialization",
				"status": "passing",
				"fixtures": [
					"init_function"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Expressions",
		"testCount": 10,
		"passingTestCount": 9,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "expr-primary",
				"section": "Primary expressions",
				"title": "Operands, selectors, indexes, slices, calls, and assertions compile",
				"status": "passing",
				"fixtures": [
					"hello_world",
					"struct_methods",
					"interface_type_assertion",
					"full_slice_expression"
				],
				"reason": ""
			},
			{
				"id": "expr-selectors",
				"section": "Selectors",
				"title": "Selector expressions resolve package names, fields, and methods",
				"status": "passing",
				"fixtures": [
					"import_internal_calls",
					"struct_methods",
					"method_expression"
				],
				"reason": ""
			},
			{
				"id": "expr-index",
				"section": "Index expressions",
				"title": "Index expressions read and write arrays, slices, strings, and maps",
				"status": "passing",
				"fixtures": [
					"named_array_index_assignment",
					"string_language",
					"map_index_inc_dec"
				],
				"reason": ""
			},
			{
				"id": "expr-slice",
				"section": "Slice expressions",
				"title": "Slice expressions support two-index and full-slice forms",
				"status": "passing",
				"fixtures": [
					"full_slice_expression",
					"string_language"
				],
				"reason": ""
			},
			{
				"id": "expr-type-assertions",
				"section": "Type assertions",
				"title": "Type assertions support single-value and comma-ok forms",
				"status": "passing",
				"fixtures": [
					"interface_type_assertion",
					"interface_downcast"
				],
				"reason": ""
			},
			{
				"id": "expr-calls",
				"section": "Calls",
				"title": "Calls handle ordinary, variadic, method, and function-value targets",
				"status": "passing",
				"fixtures": [
					"variadic_function",
					"variadic_method",
					"function_values"
				],
				"reason": ""
			},
			{
				"id": "expr-conversions",
				"section": "Conversions",
				"title": "Conversions handle numeric, string, byte-slice, and rune-slice cases",
				"status": "passing",
				"fixtures": [
					"string_language",
					"math_basic",
					"rune_literals"
				],
				"reason": ""
			},
			{
				"id": "expr-operators",
				"section": "Operators",
				"title": "Arithmetic, logical, unary, and comparison operators execute",
				"status": "passing",
				"fixtures": [
					"arithmetic_operators",
					"boolean_logic",
					"unary_operators"
				],
				"reason": ""
			},
			{
				"id": "expr-precedence",
				"section": "Operator precedence",
				"title": "Operator precedence and associativity preserve Go grouping",
				"status": "passing",
				"fixtures": [
					"operator_precedence",
					"deeply_nested_expressions"
				],
				"reason": ""
			},
			{
				"id": "expr-evaluation-order",
				"section": "Order of evaluation",
				"title": "Evaluation order is preserved for side-effecting expressions",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs focused side-effect fixtures across calls, indexing, map updates, and multi-assignment."
			}
		]
	},
	{
		"name": "Statements",
		"testCount": 16,
		"passingTestCount": 15,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "stmt-empty-expression",
				"section": "Statements",
				"title": "Empty and expression statements compile",
				"status": "passing",
				"fixtures": [
					"empty_function",
					"hello_world"
				],
				"reason": ""
			},
			{
				"id": "stmt-send",
				"section": "Send statements",
				"title": "Send statements deliver values to channels",
				"status": "passing",
				"fixtures": [
					"channel_basic",
					"goroutine_channel"
				],
				"reason": ""
			},
			{
				"id": "stmt-inc-dec",
				"section": "IncDec statements",
				"title": "Increment and decrement statements mutate variables and indexes",
				"status": "passing",
				"fixtures": [
					"for_loop_example",
					"map_index_inc_dec"
				],
				"reason": ""
			},
			{
				"id": "stmt-assignments",
				"section": "Assignments",
				"title": "Simple, compound, and multi-value assignments execute",
				"status": "passing",
				"fixtures": [
					"multiple_assignment",
					"arithmetic_operators",
					"multi_return"
				],
				"reason": ""
			},
			{
				"id": "stmt-if",
				"section": "If statements",
				"title": "if statements support init clauses and nested branches",
				"status": "passing",
				"fixtures": [
					"if_init_statement",
					"nested_if_else"
				],
				"reason": ""
			},
			{
				"id": "stmt-switch",
				"section": "Switch statements",
				"title": "Expression switches support breaks, defaults, and fallthrough",
				"status": "passing",
				"fixtures": [
					"switch_basic",
					"switch_empty",
					"switch_fallthrough",
					"switch_break"
				],
				"reason": ""
			},
			{
				"id": "stmt-type-switch",
				"section": "Type switch statements",
				"title": "Type switches bind matched dynamic values once",
				"status": "passing",
				"fixtures": [
					"type_switch_binding",
					"type_switch_eval_once",
					"type_switch_init"
				],
				"reason": ""
			},
			{
				"id": "stmt-select",
				"section": "Select statements",
				"title": "select statements choose channel communication cases",
				"status": "passing",
				"fixtures": [
					"select_break",
					"goto_select_case",
					"goto_select_channel_case"
				],
				"reason": ""
			},
			{
				"id": "stmt-for",
				"section": "For statements",
				"title": "for loops support clauses, while-style conditions, break, and continue",
				"status": "passing",
				"fixtures": [
					"for_loop_example",
					"while_loop",
					"loop_break",
					"loop_continue"
				],
				"reason": ""
			},
			{
				"id": "stmt-range",
				"section": "For statements with range clause",
				"title": "range supports arrays, slices, maps, strings, channels, integers, and functions",
				"status": "passing",
				"fixtures": [
					"range_array_pointer",
					"range_map",
					"range_string",
					"range_channel",
					"range_integer",
					"range_function"
				],
				"reason": ""
			},
			{
				"id": "stmt-go",
				"section": "Go statements",
				"title": "go statements start concurrent function execution",
				"status": "passing",
				"fixtures": [
					"goroutine_channel",
					"goroutine_capture_mutation"
				],
				"reason": ""
			},
			{
				"id": "stmt-defer",
				"section": "Defer statements",
				"title": "defer statements run in last-in-first-out order",
				"status": "passing",
				"fixtures": [
					"multiple_defer"
				],
				"reason": ""
			},
			{
				"id": "stmt-return",
				"section": "Return statements",
				"title": "return statements support explicit and named return values",
				"status": "passing",
				"fixtures": [
					"early_return",
					"named_return",
					"multi_return"
				],
				"reason": ""
			},
			{
				"id": "stmt-branch",
				"section": "Break statements",
				"title": "break and continue target innermost or labeled loops",
				"status": "passing",
				"fixtures": [
					"labeled_break",
					"labeled_continue_post",
					"loop_break",
					"loop_continue"
				],
				"reason": ""
			},
			{
				"id": "stmt-goto",
				"section": "Goto statements",
				"title": "goto statements target labels without entering invalid scopes",
				"status": "passing",
				"fixtures": [
					"goto_backward",
					"goto_forward_local",
					"goto_switch_case"
				],
				"reason": ""
			},
			{
				"id": "stmt-arbitrary-forward-goto",
				"section": "Goto statements",
				"title": "Arbitrary forward goto lowers across complex statement graphs",
				"status": "skipped",
				"fixtures": [],
				"reason": "Current support is limited to direct statement-list state-loop lowering."
			}
		]
	},
	{
		"name": "Built-in functions",
		"testCount": 9,
		"passingTestCount": 8,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "builtin-append-copy",
				"section": "Appending to and copying slices",
				"title": "append and copy mutate and return slices correctly",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "builtin-len-cap",
				"section": "Length and capacity",
				"title": "len and cap report values for strings, arrays, slices, maps, and channels",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin",
					"full_slice_expression"
				],
				"reason": ""
			},
			{
				"id": "builtin-make-new",
				"section": "Making slices, maps and channels",
				"title": "make and new allocate slices, maps, channels, and pointer values",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin",
					"pointer_basic"
				],
				"reason": ""
			},
			{
				"id": "builtin-delete-clear",
				"section": "Deleting map elements",
				"title": "delete and clear update maps and slices",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "builtin-complex-real-imag",
				"section": "Manipulating complex numbers",
				"title": "complex, real, and imag construct and decompose complex values",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin",
					"complex_types"
				],
				"reason": ""
			},
			{
				"id": "builtin-max-min",
				"section": "Min and max",
				"title": "max and min choose ordered values",
				"status": "passing",
				"fixtures": [
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "builtin-panic-recover",
				"section": "Handling panics",
				"title": "panic and recover follow deferred recovery semantics",
				"status": "skipped",
				"fixtures": [],
				"reason": "Generated programs still model only panic output paths, not full recover semantics."
			},
			{
				"id": "builtin-print-println",
				"section": "Bootstrapping",
				"title": "print and println emit values",
				"status": "passing",
				"fixtures": [
					"hello_world",
					"gostdlib_fmt",
					"gostdlib_builtin"
				],
				"reason": ""
			},
			{
				"id": "builtin-close",
				"section": "Channel types",
				"title": "close marks a channel closed and receive observes closure",
				"status": "passing",
				"fixtures": [
					"channel_comma_ok"
				],
				"reason": ""
			}
		]
	},
	{
		"name": "Packages and program initialization",
		"testCount": 5,
		"passingTestCount": 4,
		"skippedTestCount": 1,
		"tests": [
			{
				"id": "packages-single-main",
				"section": "Program execution",
				"title": "A main package with main.main executes",
				"status": "passing",
				"fixtures": [
					"hello_world"
				],
				"reason": ""
			},
			{
				"id": "packages-multiple-files",
				"section": "Packages",
				"title": "Multiple files in one package compile together",
				"status": "passing",
				"fixtures": [
					"multi_file_same_package",
					"import_multi_file_package"
				],
				"reason": ""
			},
			{
				"id": "packages-import-paths",
				"section": "Import declarations",
				"title": "Import paths resolve local packages and nested packages",
				"status": "passing",
				"fixtures": [
					"import_local_package",
					"import_nested_package",
					"import_multiple_packages"
				],
				"reason": ""
			},
			{
				"id": "packages-stdlib-imports",
				"section": "Import declarations",
				"title": "Standard-library imports resolve through embedded Go source",
				"status": "passing",
				"fixtures": [
					"gostdlib_fmt",
					"gostdlib_strings",
					"gostdlib_strconv"
				],
				"reason": ""
			},
			{
				"id": "packages-initialization-order",
				"section": "Program initialization and execution",
				"title": "Package initialization runs dependencies, variables, and init functions in order",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs multi-package ordering fixtures with observable init side effects."
			}
		]
	},
	{
		"name": "Generics",
		"testCount": 5,
		"passingTestCount": 3,
		"skippedTestCount": 2,
		"tests": [
			{
				"id": "generics-functions",
				"section": "Function declarations",
				"title": "Generic functions instantiate and execute",
				"status": "passing",
				"fixtures": [
					"generics_basic"
				],
				"reason": ""
			},
			{
				"id": "generics-types",
				"section": "Type declarations",
				"title": "Generic named types instantiate and expose methods",
				"status": "passing",
				"fixtures": [
					"generic_type_method"
				],
				"reason": ""
			},
			{
				"id": "generics-receiver-methods",
				"section": "Method declarations",
				"title": "Generic receiver methods keep receiver type parameters",
				"status": "passing",
				"fixtures": [
					"generic_type_method"
				],
				"reason": ""
			},
			{
				"id": "generics-constraints",
				"section": "Interface types",
				"title": "Constraint interfaces and type sets restrict type arguments",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs semantic validation and lowering for type-set operations beyond current generic fixtures."
			},
			{
				"id": "generics-type-inference",
				"section": "Instantiations",
				"title": "Type inference chooses type arguments for generic calls",
				"status": "skipped",
				"fixtures": [],
				"reason": "Needs fixtures where type arguments are omitted and inferred from operands/results."
			}
		]
	}
];

export const specConformanceSummary = {
	"categoryCount": 12,
	"passingCategoryCount": 2,
	"testCount": 102,
	"passingTestCount": 87,
	"skippedTestCount": 15
} as const;
