on:
  pull_request:
  push:

name: ci

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- --deny warnings

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: lexer -- --nocapture --test-threads=1

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js toolchain
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Building WASM package
        working-directory: ./gors-wasm
        run: wasm-pack build

      - name: Install www dependencies
        working-directory: ./www
        run: npm ci

      - name: Build www
        working-directory: ./www
        run: npm run build

      - name: Deploy www
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./www/dist
