name: ci
on: [push, pull_request]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- --deny warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --lib

      - name: run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --bin gors lexer -- --nocapture --test-threads=1

  build-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Node.js toolchain
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build gors-wasm
        working-directory: ./gors-wasm
        run: wasm-pack build --release

      - name: Install www dependencies
        working-directory: ./www
        run: npm ci

      - name: Build www
        working-directory: ./www
        run: npm run build

      - uses: actions/upload-artifact@v2
        with:
          name: www-dist
          path: ./www/dist

  deploy-www:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [lint, build, test, build-www]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: www-dist
          path: ./www/dist

      - name: Deploy www
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./www/dist
          clean: true
