name: ci
on: [push, pull_request]
jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run `cargo fmt`
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run `cargo clippy`
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run `cargo build`
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features --release

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Go toolchain
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Run unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features --workspace --exclude=gors-cli

      - name: Run integration tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets --all-features --workspace --package=gors-cli lexer -- --nocapture --test-threads=1

  www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Node.js toolchain
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build gors-wasm
        working-directory: ./gors-wasm
        run: wasm-pack build --release

      - name: Install www dependencies
        working-directory: ./www
        run: npm ci

      - name: Lint www code
        working-directory: ./www
        run: npm run lint

      - name: Build www code
        working-directory: ./www
        run: npm run build

      - name: Upload the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: www-dist
          path: ./www/dist

  deploy-www:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: [lint, build, test, www]
    steps:
      - uses: actions/checkout@v2

      - name: Download the build artifacts
        uses: actions/download-artifact@v2
        with:
          name: www-dist
          path: ./www/dist

      - name: Deploy www
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./www/dist
          clean: true
