on:
  push:

name: www

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node.js toolchain
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install wasm-pack
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: wasm-pack

      - name: Building WASM package
        working-directory: ./gors-wasm
        run: wasm-pack build

      - name: Install www dependencies
        working-directory: ./www
        run: npm install

      - name: Build www
        working-directory: ./www
        run: npm run build

      - name: Deploy www
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: ./www/dist
